version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3350
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: Strapi123
      DATABASE_SSL: 'false'
    volumes:
      - ./app:/srv/app
    networks:
      - strapi
    ports:
      - '1337:1337'
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    build: ./db
    # Set max_allowed_packet to 256M (or any other value)
    command: --max_allowed_packet=32505856
    environment:
        MYSQL_DATABASE: strapi
        MYSQL_ROOT_PASSWORD: Strapi123
        MYSQL_USER: strapi
        MYSQL_PASSWORD: Strapi123
    ports:
        - "3350:3306"
    volumes:
        - ./mysql_data:/var/lib/mysql:z
    networks:
        - strapi
    restart: on-failure

networks:
    strapi:
        driver: bridge